-- Set the timezone for the database session
SET timezone = 'Asia/Dhaka';

-- Create the news table with RLS enabled and Bangladesh timezone
CREATE TABLE public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    headline VARCHAR(255) NOT NULL,
    story TEXT NOT NULL,
    summary TEXT,
    bullet_points TEXT[],
    image_link TEXT,
    source_link TEXT NOT NULL UNIQUE,
    meta_description TEXT,
    meta_keywords TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (now() AT TIME ZONE 'Asia/Dhaka') NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now() AT TIME ZONE 'Asia/Dhaka') NOT NULL
);

-- Create indexes for common query patterns
CREATE INDEX idx_news_source_category_created 
    ON public.news(source_name, category, created_at DESC);

CREATE INDEX idx_news_headline 
    ON public.news USING GIN (headline gin_trgm_ops);

-- Enable the pg_trgm extension for better text search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Create updated_at trigger with Bangladesh timezone
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = (now() AT TIME ZONE 'Asia/Dhaka');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Function to get current Bangladesh time
CREATE OR REPLACE FUNCTION public.get_bangladesh_time()
RETURNS TIMESTAMP WITH TIME ZONE AS $$
BEGIN
    RETURN (now() AT TIME ZONE 'Asia/Dhaka');
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_news_updated
    BEFORE UPDATE ON public.news
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();

-- Enable Row Level Security (RLS)
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- Create policies for different operations
CREATE POLICY "Allow public read access"
    ON public.news
    FOR SELECT
    TO public
    USING (true);

CREATE POLICY "Allow authenticated insert"
    ON public.news
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Allow authenticated update"
    ON public.news
    FOR UPDATE
    TO authenticated
    USING (auth.uid() IN (
        SELECT auth.uid() 
        FROM auth.users 
        WHERE auth.users.id = auth.uid()
    ));

-- Comments for better documentation
COMMENT ON TABLE public.news IS 'Table storing news articles with metadata (Bangladesh timezone)';